eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME}:8761/eureka
name:
  value: micromall
spring:
  cloud:
    config:
      override-system-properties: false