eureka:
  instance:
    hostname: micromall-discovery-server
  client:
    service-url:
      defaultZone: http://micromall-discovery-server:8761/eureka
name:
  value: micromall
spring:
  cloud:
    config:
      override-system-properties: false