spring:
    data:
        mongodb:
            username: marouane
            password: marouane
            database: customer
            host: localhost
            port: 27017
            authentication-database: admin
server:
    port: 8081